# Generated by Django 4.2.5 on 2023-09-17 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ebook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("book_name", models.CharField(max_length=100)),
                ("autor", models.CharField(max_length=100)),
                ("translator", models.CharField(max_length=100)),
                ("publisher", models.CharField(max_length=100)),
                ("publisher_data", models.CharField(max_length=100)),
                ("price", models.CharField(max_length=20)),
                ("rating_nums", models.CharField(max_length=10)),
                ("rating_people", models.CharField(max_length=10)),
                ("comment", models.CharField(max_length=200)),
                ("book_num", models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name="Book",
        ),
    ]
