# Generated by Django 4.2.5 on 2023-09-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookapp", "0003_ebook_book_img"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reader", models.CharField(max_length=255)),
                ("star", models.CharField(max_length=255)),
                ("time", models.CharField(max_length=255)),
                ("short_comm", models.TextField()),
                ("read_img", models.CharField(max_length=255)),
                ("book_img", models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="ebook",
            name="book_img",
        ),
    ]
