# Generated by Django 4.2.5 on 2023-09-18 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookapp", "0004_bookcomment_remove_ebook_book_img"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BookComment",
            new_name="BookComments",
        ),
        migrations.RenameField(
            model_name="bookcomments",
            old_name="book_img",
            new_name="book_imgs",
        ),
    ]
