# Generated by Django 4.2.5 on 2023-09-19 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookapp", "0007_rename_book_id_bookcomment_ebook_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ebook",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
