# Generated by Django 4.2.5 on 2023-09-20 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookapp", "0008_alter_ebook_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookcomment",
            old_name="ebook_id",
            new_name="ebook",
        ),
        migrations.AddField(
            model_name="bookcomment",
            name="value",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
