# Generated by Django 4.2.5 on 2023-09-20 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookapp", "0009_rename_ebook_id_bookcomment_ebook_bookcomment_value"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookcomment",
            old_name="value",
            new_name="percent_type",
        ),
    ]
