# Generated by Django 4.2.5 on 2023-09-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookapp", "0010_rename_value_bookcomment_percent_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="ebook",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
    ]
